#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

FIXTURE="${RUNNER_TEMP:-/tmp}/schneeglass-release-checksum-manifest-fixture"
rm -rf "$FIXTURE"
mkdir -p "$FIXTURE"

EXPECTED='SchneeGlass-0.1.0.zip'
DECOY='SchneeGlass-0x1y0zzip'
OUTPUT="$FIXTURE/output.log"
REAL_GREP="$(command -v grep)"

printf '%s\n' 'expected signed archive fixture' > "$FIXTURE/$EXPECTED"
printf '%s\n' 'decoy archive fixture' > "$FIXTURE/$DECOY"

# Control: the exact one-entry manifest generated by production release creation is accepted.
(
  cd "$FIXTURE"
  shasum -a 256 "$EXPECTED" > SHA256SUMS
)
bash Scripts/verify-release-checksum-manifest.sh "$FIXTURE" "$EXPECTED" >/dev/null

# RED reproduction for the old publication semantics:
# dots in the expected archive name were unescaped ERE wildcards, so a checksum entry for
# a different existing filename could satisfy grep while shasum verified only that decoy.
(
  cd "$FIXTURE"
  shasum -a 256 "$DECOY" > SHA256SUMS
)

"$REAL_GREP" -E "^[0-9a-fA-F]{64}  ${EXPECTED}$" "$FIXTURE/SHA256SUMS" >/dev/null
(
  cd "$FIXTURE"
  shasum -a 256 -c SHA256SUMS >/dev/null
)

set +e
bash Scripts/verify-release-checksum-manifest.sh "$FIXTURE" "$EXPECTED" >"$OUTPUT" 2>&1
STATUS=$?
set -e

if [[ "$STATUS" -eq 0 ]]; then
  cat "$OUTPUT"
  echo 'Release checksum verifier unexpectedly accepted a decoy manifest entry.' >&2
  exit 1
fi

"$REAL_GREP" -Fq \
  "Release checksum manifest verification failed: SHA256SUMS archive entry mismatch: expected $EXPECTED, found $DECOY" \
  "$OUTPUT"

# The production contract is one archive and one manifest entry. Extra entries are rejected
# even when every listed checksum is internally valid.
(
  cd "$FIXTURE"
  shasum -a 256 "$EXPECTED" > SHA256SUMS
  shasum -a 256 "$DECOY" >> SHA256SUMS
)

set +e
bash Scripts/verify-release-checksum-manifest.sh "$FIXTURE" "$EXPECTED" >"$OUTPUT" 2>&1
STATUS=$?
set -e

if [[ "$STATUS" -eq 0 ]]; then
  cat "$OUTPUT"
  echo 'Release checksum verifier unexpectedly accepted multiple manifest entries.' >&2
  exit 1
fi

"$REAL_GREP" -Fq \
  'Release checksum manifest verification failed: SHA256SUMS must contain exactly one entry; found 2' \
  "$OUTPUT"

rm -rf "$FIXTURE"
echo 'Release checksum manifest fixture passed'
